---
apiVersion: v1
kind: Service
metadata:
  name: edo-consumer-v1
  namespace: odex
  labels:
    app: odex
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    demo: ODeX-Edo-Consumer-V1
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
---
apiVersion: v1
kind: Service
metadata:
  name: edo-consumer-v2
  namespace: odex
  labels:
    app: odex
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    demo: ODeX-Edo-Consumer-V2
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
---
apiVersion: v1
kind: Service
metadata:
  name: edo-rest-v1
  namespace: odex
  labels:
    app: odex
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    demo: ODeX-Edo-Rest-V1
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
---
apiVersion: v1
kind: Service
metadata:
  name: edo-rest-v2
  namespace: odex
  labels:
    app: odex
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    demo: ODeX-Edo-Rest-V2
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
---
apiVersion: v1
kind: Service
metadata:
  name: payment-gateway
  namespace: odex
  labels:
    app: odex
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    demo: ODEX-Payment-gateway
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
---